export const FETCH_DATA = "FETCH_DATA";
export const LOCATION_WEATHER = "LOCATION_WEATHER";
export const FIVE_DAYS_WEATHER = "FIVE_DAYS_WEATHER";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const CURRENT_WEATHER = "CURRENT_WEATHER";
export const TOGGLE_NIGHT_MODE = "TOGGLE_NIGHT_MODE";
export const TOGGLE_CELSIUS_MODE = "TOGGLE_CELSIUS_MODE";
